workspace:
  base: /go
  path: src/github.com/fbcbarbosa/hello

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - echo ${DRONE_PREV_COMMIT_SHA}
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
  
  test:
    image: golang:1.9-alpine
    commands:
      - go test .
    when:
      event: push

  tag:
    image: alpine/git
    commands:
      - git tag 0.0.${DRONE_BUILD_NUMBER}
      - git push https://$${GITHUB_TOKEN}@github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME} 0.0.${DRONE_BUILD_NUMBER}
    secrets:
      - github_token
    when:
      event: push
      branch: master

  # Mocked staging step
  
  staging:
    image: golang:1.9-alpine
    commands:
      - go test .
    when:
      event: tag

  # If all goes well on staging...
  # we turn the tag into a release!

  release:
    image: plugins/github-release
    files: ./hello
    secrets:
      - github_token
    when:
      event: tag
