workspace:
  base: /go
  path: src/github.com/fbcbarbosa/hello

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - echo ${DRONE_PREV_COMMIT_SHA}
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
  
  test:
    image: golang:1.9-alpine
    commands:
      - go test .
    when:
      event: push

  publish:
    image: plugins/docker
    repo: fbcbarbosa/hello
    when:
      event: push
