workspace:
  base: /go
  path: src/github.com/fbcbarbosa/hello

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - echo ${DRONE_PREV_COMMIT_SHA}
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
    when:
      branch: master
